name: Docker Image CI

on:
  workflow_call:
    inputs:
      imageTag:
        required: true
        type: string
  # push:
  #   branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
