name: Build and Push Docker Image

on: 
  workflow_call:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}
  # IMAGE_TAG: 

jobs:

  build-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set short SHA
      id: vars
      run: echo "::set-output name=GITHUB_SHA_SHORT::$(git rev-parse --short HEAD)"
    - name: Check short SHA
      run: echo ${{ steps.vars.outputs.GITHUB_SHA_SHORT }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.GITHUB_SHA_SHORT }}
    - name: Push the Docker image
      run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.GITHUB_SHA_SHORT }}