name: Build and Push Docker Image

on: 
  workflow_call:
  # workflow_call:
  #   inputs:
  #     image-tag:
  #       required: true
  #       type: string
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}
  # IMAGE_TAG: 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$(date +%s)
  
  push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Push the Docker image
      run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$(date +%s)